import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Geist_Mono } from "next/font/google";
import { Anuphan } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import Header from "@/components/layout/Header";
import { BodyLayout } from "@/components/layout/BodyLayout";
import { MobileNotSupported } from "@/components/layout/MobileNotSupported";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import { HeaderVisibilityController } from "@/components/layout/HeaderVisibilityController";

// Plus Jakarta Sans - Primary font for English (Friendly + Modern Geometric)
const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
});

// Anuphan - Thai font (Modern Sans-serif with Human Touch)
const anuphan = Anuphan({
  variable: "--font-anuphan",
  subsets: ["thai", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  display: "swap",
});

// Keep Geist Mono for code blocks
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" suppressHydrationWarning>
      <body className={`${plusJakartaSans.variable} ${anuphan.variable} ${geistMono.variable} font-sans antialiased min-h-screen`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <ErrorBoundary>
            <div className="flex min-h-screen flex-col">
              <HeaderVisibilityController />
              <Header />
              <BodyLayout variant="default">
                {children}
              </BodyLayout>
            </div>
          </ErrorBoundary>
        </ThemeProvider>
      </body>
    </html>
  );
}
