package mapper

import (
	"monorepo/backend-go/internal/application/homesettings/dto"
	"monorepo/backend-go/internal/core/domain/homesettings/entity"
)

// ToDTO converts domain entity to DTO
func ToDTO(e *entity.HomeSettings) *dto.HomeSettingsDTO {
	if e == nil {
		return nil
	}

	return &dto.HomeSettingsDTO{
		ID: e.ID,
		Hero: dto.HeroSectionDTO{
			Enabled:        e.Hero.Enabled,
			Order:          e.Hero.Order,
			BadgeText:      e.Hero.BadgeText,
			BadgeIcon:      e.Hero.BadgeIcon,
			TitleHighlight: e.Hero.TitleHighlight,
			TitleRest:      e.Hero.TitleRest,
			Subtitle:       e.Hero.Subtitle,
			Feature1:       e.Hero.Feature1,
			Feature2:       e.Hero.Feature2,
			Feature3:       e.Hero.Feature3,
			CTAPrimary:     e.Hero.CTAPrimary,
			CTASecondary:   e.Hero.CTASecondary,
			CTATertiary:    e.Hero.CTATertiary,
		},
		WhatIsIt: dto.WhatIsItSectionDTO{
			Enabled:             e.WhatIsIt.Enabled,
			Order:               e.WhatIsIt.Order,
			Title:               e.WhatIsIt.Title,
			Subtitle:            e.WhatIsIt.Subtitle,
			Feature1Title:       e.WhatIsIt.Feature1Title,
			Feature1Description: e.WhatIsIt.Feature1Description,
			Feature2Title:       e.WhatIsIt.Feature2Title,
			Feature2Description: e.WhatIsIt.Feature2Description,
			Feature3Title:       e.WhatIsIt.Feature3Title,
			Feature3Description: e.WhatIsIt.Feature3Description,
		},
		SKU: dto.SKUSectionDTO{
			Enabled:   e.SKU.Enabled,
			Order:     e.SKU.Order,
			Title:     e.SKU.Title,
			Subtitle:  e.SKU.Subtitle,
			CardTitle: e.SKU.CardTitle,

			Card1Label: e.SKU.Card1Label,
			Card2Label: e.SKU.Card2Label,
			Card3Label: e.SKU.Card3Label,

			ExpressEnabled:     e.SKU.ExpressEnabled,
			ExpressBadgeText:   e.SKU.ExpressBadgeText,
			ExpressBadgeIcon:   e.SKU.ExpressBadgeIcon,
			ExpressBadgeColor:  e.SKU.ExpressBadgeColor,
			ExpressEmoji:       e.SKU.ExpressEmoji,
			ExpressName:        e.SKU.ExpressName,
			ExpressTagline:     e.SKU.ExpressTagline,
			ExpressDescription: e.SKU.ExpressDescription,
			ExpressFeature1:    e.SKU.ExpressFeature1,
			ExpressFeature2:    e.SKU.ExpressFeature2,
			ExpressFeature3:    e.SKU.ExpressFeature3,
			ExpressFeature4:    e.SKU.ExpressFeature4,
			ExpressButtonText:  e.SKU.ExpressButtonText,
			ExpressButtonLink:  e.SKU.ExpressButtonLink,
			ExpressFooterText:  e.SKU.ExpressFooterText,

			SquadEnabled:     e.SKU.SquadEnabled,
			SquadBadgeText:   e.SKU.SquadBadgeText,
			SquadBadgeIcon:   e.SKU.SquadBadgeIcon,
			SquadBadgeColor:  e.SKU.SquadBadgeColor,
			SquadEmoji:       e.SKU.SquadEmoji,
			SquadName:        e.SKU.SquadName,
			SquadTagline:     e.SKU.SquadTagline,
			SquadDescription: e.SKU.SquadDescription,
			SquadFeature1:    e.SKU.SquadFeature1,
			SquadFeature2:    e.SKU.SquadFeature2,
			SquadFeature3:    e.SKU.SquadFeature3,
			SquadFeature4:    e.SKU.SquadFeature4,
			SquadButtonText:  e.SKU.SquadButtonText,
			SquadButtonLink:  e.SKU.SquadButtonLink,
			SquadFooterText:  e.SKU.SquadFooterText,

			GreetingEnabled:     e.SKU.GreetingEnabled,
			GreetingBadgeText:   e.SKU.GreetingBadgeText,
			GreetingBadgeIcon:   e.SKU.GreetingBadgeIcon,
			GreetingBadgeColor:  e.SKU.GreetingBadgeColor,
			GreetingEmoji:       e.SKU.GreetingEmoji,
			GreetingName:        e.SKU.GreetingName,
			GreetingTagline:     e.SKU.GreetingTagline,
			GreetingDescription: e.SKU.GreetingDescription,
			GreetingFeature1:    e.SKU.GreetingFeature1,
			GreetingFeature2:    e.SKU.GreetingFeature2,
			GreetingFeature3:    e.SKU.GreetingFeature3,
			GreetingFeature4:    e.SKU.GreetingFeature4,
			GreetingButtonText:  e.SKU.GreetingButtonText,
			GreetingButtonLink:  e.SKU.GreetingButtonLink,
			GreetingFooterText:  e.SKU.GreetingFooterText,
		},
		HowItWorks: dto.HowItWorksSectionDTO{
			Enabled:          e.HowItWorks.Enabled,
			Order:            e.HowItWorks.Order,
			Title:            e.HowItWorks.Title,
			Subtitle:         e.HowItWorks.Subtitle,
			Step1Title:       e.HowItWorks.Step1Title,
			Step1Description: e.HowItWorks.Step1Description,
			Step2Title:       e.HowItWorks.Step2Title,
			Step2Description: e.HowItWorks.Step2Description,
			Step3Title:       e.HowItWorks.Step3Title,
			Step3Description: e.HowItWorks.Step3Description,
		},
		Occasions: dto.OccasionsSectionDTO{
			Enabled:       e.Occasions.Enabled,
			Order:         e.Occasions.Order,
			Title:         e.Occasions.Title,
			Subtitle:      e.Occasions.Subtitle,
			Occasion1:     e.Occasions.Occasion1,
			Occasion1Icon: e.Occasions.Occasion1Icon,
			Occasion2:     e.Occasions.Occasion2,
			Occasion2Icon: e.Occasions.Occasion2Icon,
			Occasion3:     e.Occasions.Occasion3,
			Occasion3Icon: e.Occasions.Occasion3Icon,
			Occasion4:     e.Occasions.Occasion4,
			Occasion4Icon: e.Occasions.Occasion4Icon,
			Occasion5:     e.Occasions.Occasion5,
			Occasion5Icon: e.Occasions.Occasion5Icon,
			Occasion6:     e.Occasions.Occasion6,
			Occasion6Icon: e.Occasions.Occasion6Icon,
			Occasion7:     e.Occasions.Occasion7,
			Occasion7Icon: e.Occasions.Occasion7Icon,
			Occasion8:     e.Occasions.Occasion8,
			Occasion8Icon: e.Occasions.Occasion8Icon,
			Occasion9:     e.Occasions.Occasion9,
			Occasion9Icon: e.Occasions.Occasion9Icon,
		},
		WhyNFC: dto.WhyNFCSectionDTO{
			Enabled:             e.WhyNFC.Enabled,
			Order:               e.WhyNFC.Order,
			Title:               e.WhyNFC.Title,
			Subtitle:            e.WhyNFC.Subtitle,
			Benefit1Title:       e.WhyNFC.Benefit1Title,
			Benefit1Description: e.WhyNFC.Benefit1Description,
			Benefit2Title:       e.WhyNFC.Benefit2Title,
			Benefit2Description: e.WhyNFC.Benefit2Description,
			Benefit3Title:       e.WhyNFC.Benefit3Title,
			Benefit3Description: e.WhyNFC.Benefit3Description,
			Benefit4Title:       e.WhyNFC.Benefit4Title,
			Benefit4Description: e.WhyNFC.Benefit4Description,
		},
		WhyUs: dto.WhyUsSectionDTO{
			Enabled:             e.WhyUs.Enabled,
			Order:               e.WhyUs.Order,
			Title:               e.WhyUs.Title,
			Subtitle:            e.WhyUs.Subtitle,
			Feature1Title:       e.WhyUs.Feature1Title,
			Feature1Description: e.WhyUs.Feature1Description,
			Feature2Title:       e.WhyUs.Feature2Title,
			Feature2Description: e.WhyUs.Feature2Description,
			Feature3Title:       e.WhyUs.Feature3Title,
			Feature3Description: e.WhyUs.Feature3Description,
		},
		Preview: dto.PreviewSectionDTO{
			Enabled:     e.Preview.Enabled,
			Order:       e.Preview.Order,
			Title:       e.Preview.Title,
			Subtitle:    e.Preview.Subtitle,
			Description: e.Preview.Description,
			Image:       e.Preview.Image,
		},
		FAQ: dto.FAQSectionDTO{
			Enabled:      e.FAQ.Enabled,
			Order:        e.FAQ.Order,
			Title:        e.FAQ.Title,
			Subtitle:     e.FAQ.Subtitle,
			FAQ1Question: e.FAQ.FAQ1Question,
			FAQ1Answer:   e.FAQ.FAQ1Answer,
			FAQ2Question: e.FAQ.FAQ2Question,
			FAQ2Answer:   e.FAQ.FAQ2Answer,
			FAQ3Question: e.FAQ.FAQ3Question,
			FAQ3Answer:   e.FAQ.FAQ3Answer,
			FAQ4Question: e.FAQ.FAQ4Question,
			FAQ4Answer:   e.FAQ.FAQ4Answer,
		},
		FinalCTA: dto.FinalCTASectionDTO{
			Enabled:    e.FinalCTA.Enabled,
			Order:      e.FinalCTA.Order,
			Title:      e.FinalCTA.Title,
			Subtitle:   e.FinalCTA.Subtitle,
			ButtonText: e.FinalCTA.ButtonText,
		},
		MetaTitle:       e.MetaTitle,
		MetaDescription: e.MetaDescription,
		OGTitle:         e.OGTitle,
		OGDescription:   e.OGDescription,
		OGImage:         e.OGImage,
		UpdatedBy:       e.UpdatedBy,
	}
}

// ToEntity converts DTO to domain entity
func ToEntity(d *dto.HomeSettingsDTO) *entity.HomeSettings {
	if d == nil {
		return nil
	}

	return &entity.HomeSettings{
		ID: d.ID,
		Hero: entity.HeroSection{
			Section:        entity.Section{Enabled: d.Hero.Enabled, Order: d.Hero.Order},
			BadgeText:      d.Hero.BadgeText,
			BadgeIcon:      d.Hero.BadgeIcon,
			TitleHighlight: d.Hero.TitleHighlight,
			TitleRest:      d.Hero.TitleRest,
			Subtitle:       d.Hero.Subtitle,
			Feature1:       d.Hero.Feature1,
			Feature2:       d.Hero.Feature2,
			Feature3:       d.Hero.Feature3,
			CTAPrimary:     d.Hero.CTAPrimary,
			CTASecondary:   d.Hero.CTASecondary,
			CTATertiary:    d.Hero.CTATertiary,
		},
		WhatIsIt: entity.WhatIsItSection{
			Section:             entity.Section{Enabled: d.WhatIsIt.Enabled, Order: d.WhatIsIt.Order},
			Title:               d.WhatIsIt.Title,
			Subtitle:            d.WhatIsIt.Subtitle,
			Feature1Title:       d.WhatIsIt.Feature1Title,
			Feature1Description: d.WhatIsIt.Feature1Description,
			Feature2Title:       d.WhatIsIt.Feature2Title,
			Feature2Description: d.WhatIsIt.Feature2Description,
			Feature3Title:       d.WhatIsIt.Feature3Title,
			Feature3Description: d.WhatIsIt.Feature3Description,
		},
		SKU: entity.SKUSection{
			Section:   entity.Section{Enabled: d.SKU.Enabled, Order: d.SKU.Order},
			Title:     d.SKU.Title,
			Subtitle:  d.SKU.Subtitle,
			CardTitle: d.SKU.CardTitle,

			Card1Label: d.SKU.Card1Label,
			Card2Label: d.SKU.Card2Label,
			Card3Label: d.SKU.Card3Label,

			ExpressEnabled:     d.SKU.ExpressEnabled,
			ExpressBadgeText:   d.SKU.ExpressBadgeText,
			ExpressBadgeIcon:   d.SKU.ExpressBadgeIcon,
			ExpressBadgeColor:  d.SKU.ExpressBadgeColor,
			ExpressEmoji:       d.SKU.ExpressEmoji,
			ExpressName:        d.SKU.ExpressName,
			ExpressTagline:     d.SKU.ExpressTagline,
			ExpressDescription: d.SKU.ExpressDescription,
			ExpressFeature1:    d.SKU.ExpressFeature1,
			ExpressFeature2:    d.SKU.ExpressFeature2,
			ExpressFeature3:    d.SKU.ExpressFeature3,
			ExpressFeature4:    d.SKU.ExpressFeature4,
			ExpressButtonText:  d.SKU.ExpressButtonText,
			ExpressButtonLink:  d.SKU.ExpressButtonLink,
			ExpressFooterText:  d.SKU.ExpressFooterText,

			SquadEnabled:     d.SKU.SquadEnabled,
			SquadBadgeText:   d.SKU.SquadBadgeText,
			SquadBadgeIcon:   d.SKU.SquadBadgeIcon,
			SquadBadgeColor:  d.SKU.SquadBadgeColor,
			SquadEmoji:       d.SKU.SquadEmoji,
			SquadName:        d.SKU.SquadName,
			SquadTagline:     d.SKU.SquadTagline,
			SquadDescription: d.SKU.SquadDescription,
			SquadFeature1:    d.SKU.SquadFeature1,
			SquadFeature2:    d.SKU.SquadFeature2,
			SquadFeature3:    d.SKU.SquadFeature3,
			SquadFeature4:    d.SKU.SquadFeature4,
			SquadButtonText:  d.SKU.SquadButtonText,
			SquadButtonLink:  d.SKU.SquadButtonLink,
			SquadFooterText:  d.SKU.SquadFooterText,

			GreetingEnabled:     d.SKU.GreetingEnabled,
			GreetingBadgeText:   d.SKU.GreetingBadgeText,
			GreetingBadgeIcon:   d.SKU.GreetingBadgeIcon,
			GreetingBadgeColor:  d.SKU.GreetingBadgeColor,
			GreetingEmoji:       d.SKU.GreetingEmoji,
			GreetingName:        d.SKU.GreetingName,
			GreetingTagline:     d.SKU.GreetingTagline,
			GreetingDescription: d.SKU.GreetingDescription,
			GreetingFeature1:    d.SKU.GreetingFeature1,
			GreetingFeature2:    d.SKU.GreetingFeature2,
			GreetingFeature3:    d.SKU.GreetingFeature3,
			GreetingFeature4:    d.SKU.GreetingFeature4,
			GreetingButtonText:  d.SKU.GreetingButtonText,
			GreetingButtonLink:  d.SKU.GreetingButtonLink,
			GreetingFooterText:  d.SKU.GreetingFooterText,
		},
		HowItWorks: entity.HowItWorksSection{
			Section:          entity.Section{Enabled: d.HowItWorks.Enabled, Order: d.HowItWorks.Order},
			Title:            d.HowItWorks.Title,
			Subtitle:         d.HowItWorks.Subtitle,
			Step1Title:       d.HowItWorks.Step1Title,
			Step1Description: d.HowItWorks.Step1Description,
			Step2Title:       d.HowItWorks.Step2Title,
			Step2Description: d.HowItWorks.Step2Description,
			Step3Title:       d.HowItWorks.Step3Title,
			Step3Description: d.HowItWorks.Step3Description,
		},
		Occasions: entity.OccasionsSection{
			Section:       entity.Section{Enabled: d.Occasions.Enabled, Order: d.Occasions.Order},
			Title:         d.Occasions.Title,
			Subtitle:      d.Occasions.Subtitle,
			Occasion1:     d.Occasions.Occasion1,
			Occasion1Icon: d.Occasions.Occasion1Icon,
			Occasion2:     d.Occasions.Occasion2,
			Occasion2Icon: d.Occasions.Occasion2Icon,
			Occasion3:     d.Occasions.Occasion3,
			Occasion3Icon: d.Occasions.Occasion3Icon,
			Occasion4:     d.Occasions.Occasion4,
			Occasion4Icon: d.Occasions.Occasion4Icon,
			Occasion5:     d.Occasions.Occasion5,
			Occasion5Icon: d.Occasions.Occasion5Icon,
			Occasion6:     d.Occasions.Occasion6,
			Occasion6Icon: d.Occasions.Occasion6Icon,
			Occasion7:     d.Occasions.Occasion7,
			Occasion7Icon: d.Occasions.Occasion7Icon,
			Occasion8:     d.Occasions.Occasion8,
			Occasion8Icon: d.Occasions.Occasion8Icon,
			Occasion9:     d.Occasions.Occasion9,
			Occasion9Icon: d.Occasions.Occasion9Icon,
		},
		WhyNFC: entity.WhyNFCSection{
			Section:             entity.Section{Enabled: d.WhyNFC.Enabled, Order: d.WhyNFC.Order},
			Title:               d.WhyNFC.Title,
			Subtitle:            d.WhyNFC.Subtitle,
			Benefit1Title:       d.WhyNFC.Benefit1Title,
			Benefit1Description: d.WhyNFC.Benefit1Description,
			Benefit2Title:       d.WhyNFC.Benefit2Title,
			Benefit2Description: d.WhyNFC.Benefit2Description,
			Benefit3Title:       d.WhyNFC.Benefit3Title,
			Benefit3Description: d.WhyNFC.Benefit3Description,
			Benefit4Title:       d.WhyNFC.Benefit4Title,
			Benefit4Description: d.WhyNFC.Benefit4Description,
		},
		WhyUs: entity.WhyUsSection{
			Section:             entity.Section{Enabled: d.WhyUs.Enabled, Order: d.WhyUs.Order},
			Title:               d.WhyUs.Title,
			Subtitle:            d.WhyUs.Subtitle,
			Feature1Title:       d.WhyUs.Feature1Title,
			Feature1Description: d.WhyUs.Feature1Description,
			Feature2Title:       d.WhyUs.Feature2Title,
			Feature2Description: d.WhyUs.Feature2Description,
			Feature3Title:       d.WhyUs.Feature3Title,
			Feature3Description: d.WhyUs.Feature3Description,
		},
		Preview: entity.PreviewSection{
			Section:     entity.Section{Enabled: d.Preview.Enabled, Order: d.Preview.Order},
			Title:       d.Preview.Title,
			Subtitle:    d.Preview.Subtitle,
			Description: d.Preview.Description,
			Image:       d.Preview.Image,
		},
		FAQ: entity.FAQSection{
			Section:      entity.Section{Enabled: d.FAQ.Enabled, Order: d.FAQ.Order},
			Title:        d.FAQ.Title,
			Subtitle:     d.FAQ.Subtitle,
			FAQ1Question: d.FAQ.FAQ1Question,
			FAQ1Answer:   d.FAQ.FAQ1Answer,
			FAQ2Question: d.FAQ.FAQ2Question,
			FAQ2Answer:   d.FAQ.FAQ2Answer,
			FAQ3Question: d.FAQ.FAQ3Question,
			FAQ3Answer:   d.FAQ.FAQ3Answer,
			FAQ4Question: d.FAQ.FAQ4Question,
			FAQ4Answer:   d.FAQ.FAQ4Answer,
		},
		FinalCTA: entity.FinalCTASection{
			Section:    entity.Section{Enabled: d.FinalCTA.Enabled, Order: d.FinalCTA.Order},
			Title:      d.FinalCTA.Title,
			Subtitle:   d.FinalCTA.Subtitle,
			ButtonText: d.FinalCTA.ButtonText,
		},
		MetaTitle:       d.MetaTitle,
		MetaDescription: d.MetaDescription,
		OGTitle:         d.OGTitle,
		OGDescription:   d.OGDescription,
		OGImage:         d.OGImage,
		UpdatedBy:       d.UpdatedBy,
	}
}
